# Generated by Django 6.0.3 on 2026-04-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='expense',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='description',
            new_name='desc',
        ),
    ]
