# Generated by Django 6.0.4 on 2026-04-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_rename_expense_budget_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.IntegerField(),
        ),
    ]
