# Generated by Django 6.0.4 on 2026-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_project_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='task',
            field=models.CharField(max_length=200),
        ),
    ]
