# Generated by Django 6.0.4 on 2026-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_remove_project_progress_budget_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
