# Generated by Django 6.0.4 on 2026-04-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_budget_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
    ]
