# Generated by Django 6.0.4 on 2026-04-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_remove_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reset_total',
            field=models.BooleanField(default=False),
        ),
    ]
