# Generated by Django 6.0.4 on 2026-04-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_project_reset_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='reset_total',
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
