# Generated by Django 6.0.4 on 2026-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_remove_project_reset_total_project_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
